#prep for aquilo crafting
recipeTable = {"inserter":1,
"long-handed-inserter":2,
"fast-inserter":3,
"transport-belt":11,
"underground-belt": 12,
"fast-transport-belt": 13,
"fast-underground-belt": 14,
"pipe":21,
"pipe-to-ground":22,
"pump": 23,
"offshore-pump": 24,
"construction-robot":31,
"chemical-plant":32,
"thruster": 33,
"empty-water-barrel": 41,
"concrete": 42}


work =[]
work.append([
("inserter", 22),
("fast-inserter", 3),
("long-handed-inserter", 19),
("pipe", 215),
("chemical-plant", 5),
("thruster", 2),
("offshore-pump",1),
("pump",1),
("transport-belt", 10),
("fast-transport-belt", 10),
("underground-belt", 2),
("fast-underground-belt", 2),
("construction-robot", 30),
("empty-water-barrel", 100),
("concrete", 50),
("empty-water-barrel", 100),
("concrete", 50),
("empty-water-barrel", 100),
("concrete", 50),
("empty-water-barrel", 100),
("concrete", 45),
("empty-water-barrel", 270),
])