#current fulgora sequence

recipeTable = {"inserter":1,
"long-handed-inserter":2,
"fast-inserter":3,
"bulk-inserter":4,
"transport-belt":11,
"pipe":12,
"pipe-to-ground":13,
"substation":21,
"lightning-rod":22,
"decider-combinator":23,
"constant-combinator":24,
"steel-chest":31,
"passive-provider-chest":32,
"requester-chest":33,
"logistic-robot":34,
"stone-furnace":41,
"boiler":42,
"heat-pipe":43,
"heating-tower":44,
"heat-exchanger":45,
"steam-turbine":46,
"assembling-machine-1":51,
"assembling-machine-2":52,
"assembling-machine-3":53,
"chemical-plant":54,
"recycler":55,
"electric-mining-drill":61,
"offshore-pump":62,
"iron-stick":71,
"refined-concrete":72,
"electromagnetic-plant":73,
"rocket-silo":74}

work =[]
work.append([("sync",1), #supplies
("electric-mining-drill",8),
("sync",2), #mining 1
("electric-mining-drill",8),
("sync",3), #mining 2
("pipe", 36),
("sync",4), #power upgrade
("electric-mining-drill",16),
("refined-concrete", 4),
("logistic-robot", 50),
("pipe", 80),
("refined-concrete", 5),
("pipe", 178),
("steam-turbine", 6),
("iron-stick", 20),
("refined-concrete", 5),
("pipe", 65),
("refined-concrete", 5) ])

work.append([("sync",1), #supplies
("electric-mining-drill",8),
("sync",2), #mining 1
("electric-mining-drill",8),
("sync",3), #mining 2
("pipe", 36),
("sync",4), #power upgrade
("electric-mining-drill",16),
("refined-concrete", 3),
("steel-chest", 13),
("requester-chest", 8),
("passive-provider-chest", 5),
("refined-concrete", 5),
("logistic-robot", 50),
("pipe", 20),
("pipe-to-ground", 1),
("chemical-plant", 6),
("pipe", 178),
("steam-turbine", 6),
("iron-stick", 20),
("refined-concrete", 5),
("pipe", 65),
("refined-concrete", 5) ])


work.append([("sync",1), #supplies
("recycler", 8),
("sync",2), #mining 1
("recycler", 8),
("sync",3), #mining 2
("pipe", 25),
("inserter", 1),
("chemical-plant", 1),
("sync",4), #power upgrade
("recycler", 16),
("pipe", 45),
("chemical-plant", 5),
("electromagnetic-plant", 1),
("logistic-robot", 50),
("pipe", 40),
("steel-chest", 13),
("passive-provider-chest", 8),
("requester-chest", 5),
("inserter", 6),
("chemical-plant", 4),
("heat-exchanger", 6),
("iron-stick", 40),
("transport-belt", 30),
("pipe", 130),
("pipe-to-ground", 6),
("lightning-rod", 2),
("substation", 2),
("pipe", 70)])

work.append([("decider-combinator", 3),
("assembling-machine-1", 8),
("assembling-machine-2", 8),
("inserter",10),
("sync",1), #supplies
("steel-chest", 8),
("passive-provider-chest", 8),
("substation", 1),
("lightning-rod",1),
("pipe",30),
("chemical-plant", 1),
("sync",2), #mining 1
("steel-chest", 8),
("passive-provider-chest", 8),
("substation", 1),
("lightning-rod",1),
("offshore-pump", 2),
("sync",3), #mining 2
("steam-turbine", 3),
("heat-exchanger", 2),
("sync",4), #power upgrade
("substation", 2),
("lightning-rod",2),
("steel-chest", 16),
("passive-provider-chest", 16),
("inserter", 11),
("long-handed-inserter", 2),
("fast-inserter", 5),
("bulk-inserter", 2),
("substation", 4),
("decider-combinator", 3),
("constant-combinator",1),
("assembling-machine-1", 6),
("assembling-machine-2", 6),
("decider-combinator", 1),
("steel-chest", 3),
("passive-provider-chest", 3),
("inserter", 6),
("recycler", 1),
("substation", 3),
("lightning-rod", 1),
("inserter", 33),
("assembling-machine-1", 24),
("assembling-machine-2", 24),
("lightning-rod", 2),
("substation", 2),
("stone-furnace", 4),
("boiler", 4),
("heat-pipe", 10),
("heating-tower", 2),
("steel-chest", 2),
("requester-chest", 2),
("assembling-machine-3", 4),
("inserter", 5),
("fast-inserter", 1),
("steel-chest", 2),
("requester-chest", 2),
("inserter", 43),
("long-handed-inserter", 20),
("fast-inserter", 5),
("bulk-inserter", 2),
("assembling-machine-1", 18),
("assembling-machine-2", 18),
("offshore-pump", 1),
("recycler", 1),
("steel-chest", 5),
("requester-chest", 4),
("passive-provider-chest", 1),
("chemical-plant", 1),
("inserter", 2),
("substation", 1),
("steel-chest", 1),
("requester-chest", 1),
("rocket-silo", 2),
("recycler", 1),
("nuclear-reactor", 4)])



#synclocked fulgora sequence
recipeTable = {"inserter":1,
"long-handed-inserter":2,
"fast-inserter":3,
"bulk-inserter":4,
"transport-belt":11,
"pipe":12,
"pipe-to-ground":13,
"substation":21,
"lightning-rod":22,
"decider-combinator":23,
"constant-combinator":24,
"steel-chest":31,
"passive-provider-chest":32,
"requester-chest":33,
"logistic-robot":34,
"repair-pack":35,
"stone-furnace":41,
"boiler":42,
"heat-pipe":43,
"heating-tower":44,
"heat-exchanger":45,
"steam-turbine":46,
"assembling-machine-1":51,
"assembling-machine-2":52,
"assembling-machine-3":53,
"chemical-plant":54,
"recycler":55,
"electric-mining-drill":61,
"offshore-pump":62,
"iron-stick":71,
"refined-concrete":72,
"electromagnetic-plant":73,
"rocket-silo":74,
"nuclear-reactor":75}

work =[]
work.append([("sync",1), #supplies
("electric-mining-drill",8),
("sync",2), #mining 1
("electric-mining-drill",8),
("sync",3), #mining 2
("pipe", 36),
("sync",4), #power upgrade
("electric-mining-drill",16),
("refined-concrete", 4),
("logistic-robot", 50),
("pipe", 80),
("refined-concrete", 5),
("pipe", 178),
("steam-turbine", 6),
("iron-stick", 20),
("refined-concrete", 5),
("pipe", 65),
("refined-concrete", 5),
("sync", 5),
("substation", 1),
("lightning-rod",1),
("decider-combinator", 3),
("constant-combinator",1),
("steel-chest", 3),
("requester-chest", 2),
("passive-provider-chest", 1),
("inserter",6),
("fast-inserter", 2)])

work.append([("sync",1), #supplies
("electric-mining-drill",8),
("sync",2), #mining 1
("electric-mining-drill",8),
("sync",3), #mining 2
("pipe", 36),
("sync",4), #power upgrade
("electric-mining-drill",16),
("refined-concrete", 3),
("steel-chest", 13),
("requester-chest", 8),
("passive-provider-chest", 5),
("refined-concrete", 5),
("logistic-robot", 50),
("pipe", 20),
("pipe-to-ground", 1),
("chemical-plant", 6),
("pipe", 178),
("steam-turbine", 6),
("iron-stick", 20),
("refined-concrete", 5),
("pipe", 65),
("refined-concrete", 5),
("sync", 5),
("recycler", 1),
("repair-pack", 80)])


work.append([("sync",1), #supplies
("recycler", 8),
("sync",2), #mining 1
("recycler", 8),
("sync",3), #mining 2
("pipe", 25),
("inserter", 1),
("chemical-plant", 1),
("sync",4), #power upgrade
("recycler", 16),
("pipe", 45),
("chemical-plant", 5),
("electromagnetic-plant", 1),
("logistic-robot", 50),
("pipe", 40),
("steel-chest", 13),
("passive-provider-chest", 8),
("requester-chest", 5),
("inserter", 6),
("chemical-plant", 4),
("heat-exchanger", 6),
("iron-stick", 40),
("transport-belt", 30),
("pipe", 130),
("pipe-to-ground", 6),
("lightning-rod", 2),
("substation", 2),
("pipe", 70),
("sync", 5),
("nuclear-reactor", 2)])

work.append([("decider-combinator", 3),
("assembling-machine-1", 8),
("assembling-machine-2", 8),
("inserter",10),
("sync",1), #supplies
("steel-chest", 8),
("passive-provider-chest", 8),
("substation", 1),
("lightning-rod",1),
("pipe",30),
("chemical-plant", 1),
("sync",2), #mining 1
("steel-chest", 8),
("passive-provider-chest", 8),
("substation", 1),
("lightning-rod",1),
("offshore-pump", 2),
("sync",3), #mining 2
("steam-turbine", 3),
("heat-exchanger", 2),
("sync",4), #power upgrade
("substation", 2),
("lightning-rod",2),
("steel-chest", 16),
("passive-provider-chest", 16),
("inserter", 11),
("long-handed-inserter", 2),
("fast-inserter", 5),
("bulk-inserter", 2),
("substation", 4),
("decider-combinator", 3),
("constant-combinator",1),
("assembling-machine-1", 6),
("assembling-machine-2", 6),
("decider-combinator", 1),
("steel-chest", 3),
("passive-provider-chest", 3),
("inserter", 6),
("recycler", 1),
("substation", 3),
("lightning-rod", 1),
("inserter", 33),
("assembling-machine-1", 24),
("assembling-machine-2", 24),
("lightning-rod", 2),
("substation", 2),
("stone-furnace", 4),
("boiler", 4),
("heat-pipe", 10),
("heating-tower", 2),
("steel-chest", 2),
("requester-chest", 2),
("assembling-machine-3", 4),
("inserter", 5),
("fast-inserter", 1),
("steel-chest", 2),
("requester-chest", 2),
("inserter", 43),
("long-handed-inserter", 20),
("fast-inserter", 5),
("bulk-inserter", 2),
("assembling-machine-1", 18),
("assembling-machine-2", 18),
("offshore-pump", 1),
("recycler", 1),
("steel-chest", 5),
("requester-chest", 4),
("passive-provider-chest", 1),
("chemical-plant", 1),
("inserter", 2),
("substation", 1),
("steel-chest", 1),
("requester-chest", 1),
("rocket-silo", 2),
("sync", 5),
("nuclear-reactor", 2)])